### PR TITLE
German (Du) language pack

### PR DESCRIPTION
**Pull request by DrDeath**

### CODE REVIEW

**Comment by DrDeath** [comment]
Added in acp_statistics.php missing:
`	'NO_MESSAGE'									=> 'Keine Einträge',`

**Comment by Feneck91** [comment]
I'll see for 'NO_MESSAGE', it is used everywhere in phpBB, see to use it (and how to use it) or not.

**Comment by DrDeath** [comment]
NO_MESSAGE is only used in ucp.php: (which is not loaded in the acp)
`	'NO_MESSAGE'				=> 'Private message could not be found.',`

NO_MESSAGES is used in common.php:
`	'NO_MESSAGES'				=> 'No messages',`

Maybe you should use `NO_MESSAGES` in `adm/style/introduciator_acp_statistics.html`

I'll remote the extra language variable for now from the German language pack.
And change the `adm/style/introduciator_acp_statistics.html`

**Comment by Feneck91** [comment]
No no, I will left it. It's the better way to do this.
Thanks a lot for this bug found !

**Pull request merged**
